/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package job1;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import javafx.stage.FileChooser;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/**
 *
 * @author Wiki
 */
public class open_image extends javax.swing.JFrame {

    /**
     * Creates new form open_image
     */
    //Variabel
    String sumberGambar;
    Image image;
    Dimension size;
    BufferedImage prosesimage;

    public open_image() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fc = new javax.swing.JFileChooser();
        jFrame1 = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        image3 = new javax.swing.JLabel();
        zoom3 = new javax.swing.JSlider();
        zoomdes3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        image1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        image2 = new javax.swing.JLabel();
        zoom1 = new javax.swing.JSlider();
        zoom2 = new javax.swing.JSlider();
        zoomdes1 = new javax.swing.JTextField();
        zoomdes2 = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jFrame1.setSize(new java.awt.Dimension(300, 350));

        image3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        image3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jScrollPane3.setViewportView(image3);

        zoom3.setMaximum(400);
        zoom3.setMinimum(1);
        zoom3.setValue(1);
        zoom3.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zoom3StateChanged(evt);
            }
        });

        zoomdes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomdes3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addComponent(zoom3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zoomdes3))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zoom3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zoomdes3))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        image1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        image1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jScrollPane1.setViewportView(image1);

        image2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        image2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jScrollPane2.setViewportView(image2);

        zoom1.setMaximum(400);
        zoom1.setMinimum(1);
        zoom1.setValue(1);
        zoom1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                zoom1StateChanged(evt);
            }
        });

        zoom2.setMaximum(400);
        zoom2.setMinimum(1);
        zoom2.setValue(1);

        zoomdes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomdes1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        jMenuItem1.setText("Open");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Open in New Window");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zoom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zoomdes1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zoom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zoomdes2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(210, 269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(zoom1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zoom2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(zoomdes1)
                    .addComponent(zoomdes2))
                .addContainerGap(177, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        /* kondisi aplikasi ketika program pertama kali dijalankan
        */
        image1.setEnabled(false);
        image2.setEnabled(false);
        image3.setEnabled(false);
        zoom1.setEnabled(false);
        zoom2.setEnabled(false);
        zoom3.setEnabled(false);
        zoomdes1.setEnabled(false);
        zoomdes2.setEnabled(false);
        zoomdes3.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        // pendeklarasian variabel untuk menampilakn open dialog
        int open = fc.showOpenDialog(jPanel1);
        //kondisi jika file telah dibuka
        if (open == JFileChooser.APPROVE_OPTION) {
            /* komponen yang disable pada awal program dijalankan dienablekan 
            hanya komponen yang digunakan saja
            */
            image1.setEnabled(true);
            zoom1.setEnabled(true);
            zoomdes1.setEnabled(true);
            
            //menyimpan alamat gambar yang dibuka untuk diproses
            sumberGambar = fc.getSelectedFile().getPath();

            //proses untuk mengambil ukuran gambar sebenarnya
            image = new ImageIcon(sumberGambar).getImage();
            size = new Dimension();
            size.width = image.getWidth(null);
            size.height = image.getHeight(null);
            setPreferredSize(size);

            zoom1.setValue(100);
            
            // ukuran gambar dapat diubah dengan mengatur BufferedImage dan drawImage
            prosesimage = new BufferedImage(size.width * zoom1.getValue() / 100, size.height * zoom1.getValue() / 100, BufferedImage.TYPE_INT_RGB);
            Graphics g = prosesimage.getGraphics();
            g.drawImage(image, 0, 0, size.width * zoom1.getValue() / 100, size.height * zoom1.getValue() / 100, null);
            image1.setIcon(new ImageIcon(prosesimage));
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void zoom1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_zoom1StateChanged
        // TODO add your handling code here:
        // dengan mengubah value slider ukuran gambar dapat diperbesar dan diperkecil      
        prosesimage = new BufferedImage(size.width * zoom1.getValue() / 100, size.height * zoom1.getValue() / 100, BufferedImage.TYPE_INT_RGB);
        Graphics g = prosesimage.getGraphics();
        g.drawImage(image, 0, 0, size.width * zoom1.getValue() / 100, size.height * zoom1.getValue() / 100, null);
        zoomdes1.setText(Integer.toString(zoom1.getValue()));
        image1.setIcon(new ImageIcon(prosesimage));
    }//GEN-LAST:event_zoom1StateChanged

    private void zoomdes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomdes1ActionPerformed
        // TODO add your handling code here:
        // mengubah nilai value pada slider
        zoom1.setValue(Integer.parseInt(zoomdes1.getText()));
    }//GEN-LAST:event_zoomdes1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        // pendeklarasian variabel untuk menampilakn open dialog
        int open = fc.showOpenDialog(jPanel1);
        //kondisi jika file telah dibuka
        if (open == JFileChooser.APPROVE_OPTION) {
            //untuk menampilkan windows baru
            jFrame1.setVisible(true);
            /* komponen yang disable pada awal program dijalankan dienablekan 
            hanya komponen yang digunakan saja
            */
            image3.setEnabled(true);
            zoom3.setEnabled(true);
            zoomdes3.setEnabled(true);
            
            //menyimpan alamat gambar yang dibuka untuk diproses
            sumberGambar = fc.getSelectedFile().getPath();

            //proses untuk mengambil ukuran gambar sebenarnya
            image = new ImageIcon(sumberGambar).getImage();
            size = new Dimension();
            size.width = image.getWidth(null);
            size.height = image.getHeight(null);
            setPreferredSize(size);

            zoom3.setValue(100);

            // ukuran gambar dapat diubah dengan mengatur BufferedImage dan drawImage
            prosesimage = new BufferedImage(size.width * zoom3.getValue() / 100, size.height * zoom3.getValue() / 100, BufferedImage.TYPE_INT_RGB);
            Graphics g = prosesimage.getGraphics();
            g.drawImage(image, 0, 0, size.width * zoom3.getValue() / 100, size.height * zoom3.getValue() / 100, null);
            image3.setIcon(new ImageIcon(prosesimage));
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void zoom3StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_zoom3StateChanged
        // TODO add your handling code here:        
        // dengan mengubah value slider ukuran gambar dapat diperbesar dan diperkecil
        prosesimage = new BufferedImage(size.width * zoom3.getValue() / 100, size.height * zoom3.getValue() / 100, BufferedImage.TYPE_INT_RGB);
        Graphics g = prosesimage.getGraphics();
        g.drawImage(image, 0, 0, size.width * zoom3.getValue() / 100, size.height * zoom3.getValue() / 100, null);
        zoomdes3.setText(Integer.toString(zoom3.getValue()));
        image3.setIcon(new ImageIcon(prosesimage));
    }//GEN-LAST:event_zoom3StateChanged

    private void zoomdes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomdes3ActionPerformed
        // TODO add your handling code here:
        // mengubah nilai value pada slider
        zoom3.setValue(Integer.parseInt(zoomdes3.getText()));
    }//GEN-LAST:event_zoomdes3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(open_image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(open_image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(open_image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(open_image.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new open_image().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser fc;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image3;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider zoom1;
    private javax.swing.JSlider zoom2;
    private javax.swing.JSlider zoom3;
    private javax.swing.JTextField zoomdes1;
    private javax.swing.JTextField zoomdes2;
    private javax.swing.JTextField zoomdes3;
    // End of variables declaration//GEN-END:variables
}
